### PR TITLE
Topic/iam profile

### PR DESCRIPTION
**Pull request by andromedarabbit**
Add Kubernetes v1.3.4 and IAM Role credential support

### CODE REVIEW

**Comment by iterion** [comment]
Thanks for this! Overall, it looks great. Honestly, I think IAM Role should be the recommended setup. So, would you mind replacing the current RC example with yours?

I'll do a more thorough review and test this on our cluster soon.

**Comment by andromedarabbit** [comment]
Sounds great for me. I have no objection to that. Thanks!

**Comment by iterion** [comment]
@andromedarabbit FYI: this is still on my TODO list, just haven't gotten around to it yet, sorry!

**Comment by andromedarabbit** [comment]
No hurries

**Comment by iterion** [comment]
Worked for me, thanks!

**Pull request merged**
