### PR TITLE
Add check for existing recordset

### PR DESCRIPTION
**Pull request by aurcioli-handy**
This adds a check for existing recordset and does not trigger ChangeResourceRecordSet if the recordset already exists with the correct ELB target.

### CODE REVIEW

**Comment by iterion** [comment]
From my understanding of how AWS throttles this would make the problem we're trying to solve worse. It seems AWS throttles based on the number of requests to Route53 in general. And this change would add an additional request for each record at every 30 second tick. See: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

There is a limitation on ChangeResourceRecordSet but it seems like that would only get hit if actual changes to the records were happening quickly. It's much more likely that we're hitting the general rate limit.

Another simple solution to this would be to make the tick interval configurable through an environment variable so that users could opt to slow down updates to prevent throttling.

**Comment by iterion** [comment]
I should add, there is a new [project](https://github.com/kubernetes-incubator/external-dns) that aims to solve this problem by storing an in memory cache of what has been updated and only touches records when needed.

**Comment by aurcioli-handy** [comment]
If we are hitting the general rate limit of > 5 reqs/sec for route53 then we can add a 1s sleep between requests.

**Comment by aurcioli-handy** [comment]
I don't think the 30second tick is the problem I think its the rapid changeresourcerecordset requests on each tick. I'm looking to see now if we are in fact being rate limited at the general route53 level or for too many change resource record set requests.

**Comment by aurcioli-handy** [comment]
It looks like we could also probably change `updateDNS` to accept a list of changes and send a proper changebatch instead of 1 change per request. What do you think?

**Comment by iterion** [comment]
Sending one update would probably be ideal. Is there a limit to the number of changes in a single batch?

**Comment by aurcioli-handy** [comment]
`A request cannot contain more than 1000 ResourceRecord elements. When the value of the Action element is UPSERT, each ResourceRecord element is counted twice.`

So, 500?

**Comment by iterion** [comment]
In addition, we'd need to separate each zone into its own request.

**Pull request closed without merging**
